name: unit tests

on:
  workflow_call:
    secrets: inherit

env:
    PYTHON_VERSION: 3.10

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ env.PYTHON_VERSION }}
          uses: actions/setup-python@v3
          with:
            python-version: ${{ env.PYTHON_VERSION }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            make install
        - name: Test with pytest
          run: make test
