name: unit tests

on:
  workflow_call:

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
        strategy:
          fail-fast: false  # keep going if one job fails
          matrix:
              python-version: [3.6, 3.7, 3.8, 3.9, 3.10]
              os: [ubuntu-latest, macos-latest, windows-latest]
        steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{ env.PYTHON_VERSION }}
          uses: actions/setup-python@v3
          with:
            python-version: ${{ env.PYTHON_VERSION }}
        - name: Install dependencies
          shell: bash
          run: make install
        - name: Test with pytest
          shell: bash
          run: make test
